version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "8080"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    restart: always
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    networks:
      - backend
    command:
      [
        "redis-server",
        "--requirepass", "w24JyTn0SIEHfS",
        "--rename-command", "FLUSHALL", "",
        "--rename-command", "CONFIG", ""
      ]

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pg_admin
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@esaksham.nic.in
      PGADMIN_DEFAULT_PASSWORD: Developer123@
      SCRIPT_NAME: /pg-admin
    restart: always
    networks:
      - backend



networks:
  backend:
    driver: bridge
