"""second_migration

Revision ID: b388d6ba34aa
Revises: bfd57b00c54e
Create Date: 2025-09-24 21:23:36.020697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b388d6ba34aa'
down_revision = 'bfd57b00c54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location_specifics', ['location_specifics'], ['id'])

    with op.batch_alter_table('slopes', schema=None) as batch_op:
        batch_op.alter_column('ridge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'ridges', ['ridge_id'], ['id'])

    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('slopes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ridge_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activities_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
